### ISSUE TITLE
Comments on Lab 1

### ISSUE THREAD

**Issue by mohanty-sd** [matc-thaher/PHY5394-mohammadabuthaher#1]
- Test code does not run because it calls a missing function:
_Unrecognized function or variable 'test_4'.

Error in testatcsmgenltcsig (line 19)
sigVec = test_4(timedata,[t_a, t_a + L], A,[f_0,f_1], phase);_

- **timedata** variable should not depend on **t_a** and **L**; these are parameters of the signal
- The length of the signal is **L**: So, the highest instantaneous frequency (for positive f_1) is attained at L not 1 sec. L should be set to be less than 1 sec if the data length is 1 sec.
- The for loop to fill sample values between **t_a** and **t_a + L** is inefficient. Generate the signal between 0 and L and then fill **sigvec** between **t_a** and **t_a+L**

**Comment by matc-thaher** [comment]
Error in testatcsmgenltcsig.m (line 19)
The name of the function in variable sigVec was wrong and I corrected it.  The corrected form is:
sigVec = atcsmgenltcsig(timedata,[t_a, t_a + L], A,[f_0,f_1], phase);

- I corrected the timedata (removed t_a and L from the array). The corrected form is:
timedata = -20 : samplIntrvl : 20;

- I also determined the maximum instantaneous frequency at L ( i.e. t = t_a + L in second) and made the correction. The corrected form is:
maxinstFreq = f_0 + 2 * f_1 * L;

**Comment by matc-thaher** [comment]
- Inefficiency issue: solved by generating code inside for loop. 
"
for x = 1: length(timeData)
    if timeData(x) >= timeSteps(1) && timeData(x) <= timeSteps(2)
        phaseVec(x) = freq(1) * (timeData(x) - timeSteps(1)) + freq(2) * (timeData(x) - timeSteps(1)).^2 + (phase / (2 * pi));
        trigSin(x) = sin(2 * pi .* phaseVec(x));
        sigVec(x) = snr .* trigSin(x)/(norm(trigSin(x)));
    end
end
"

**Comment by mohanty-sd** [comment]
> * Test code does not run because it calls a missing function:
>   _Unrecognized function or variable 'test_4'.
> 
> Error in testatcsmgenltcsig (line 19)
> sigVec = test_4(timedata,[t_a, t_a + L], A,[f_0,f_1], phase);_
> 
> * **timedata** variable should not depend on **t_a** and **L**; these are parameters of the signal
> * The length of the signal is **L**: So, the highest instantaneous frequency (for positive f_1) is attained at L not 1 sec. L should be set to be less than 1 sec if the data length is 1 sec.
> * The for loop to fill sample values between **t_a** and **t_a + L** is inefficient. Generate the signal between 0 and L and then fill **sigvec** between **t_a** and **t_a+L**

Closed.
