### ISSUE TITLE
- Inefficiency issue: solved by generating code inside for loop.

### ISSUE THREAD

**Issue by mohanty-sd** [matc-thaher/PHY5394-mohammadabuthaher#2]
Actually not solved: You are still using a for loop and checking each time sample if it lies in the interval. You should be able to get the indices corresponding to timeSteps(1) and timeSteps(2) right away from the sampling interval. (Hint: How many sampling intervals lie between 0 and 2.0 sec if the sampling interval is 0.1 sec?)

- Inefficiency issue: solved by generating code inside for loop. 
"
for x = 1: length(timeData)
    if timeData(x) >= timeSteps(1) && timeData(x) <= timeSteps(2)
        phaseVec(x) = freq(1) * (timeData(x) - timeSteps(1)) + freq(2) * (timeData(x) - timeSteps(1)).^2 + (phase / (2 * pi));
        trigSin(x) = sin(2 * pi .* phaseVec(x));
        sigVec(x) = snr .* trigSin(x)/(norm(trigSin(x)));
    end
end
"

_Originally posted by @matc-thaher in https://github.com/matc-thaher/PHY5394-mohammadabuthaher/issues/1#issuecomment-773719845_

**Comment by matc-thaher** [comment]
I hope that this code will solve the time inefficiency problem. The code is given below and also uploaded into the file:
"
idxt = find(timeData>=timeSteps(1) & timeData <= timeSteps(2));
sigVec = zeros(1, length(timeData));
phaseVec = freq(1) * (timeData(idxt) - timeSteps(1)) + freq(2) * (timeData(idxt) - timeSteps(1)).^2 + (phase / (2 * pi));
trigSin = sin(2 * pi * phaseVec);
sigVec(idxt) = snr * trigSin/norm(trigSin);
"

**Comment by mohanty-sd** [comment]
> I hope that this code will solve the time inefficiency problem. The code is given below and also uploaded into the file:
> "
> idxt = find(timeData>=timeSteps(1) & timeData <= timeSteps(2));
> sigVec = zeros(1, length(timeData));
> phaseVec = freq(1) * (timeData(idxt) - timeSteps(1)) + freq(2) * (timeData(idxt) - timeSteps(1)).^2 + (phase / (2 * pi));
> trigSin = sin(2 * pi * phaseVec);
> sigVec(idxt) = snr * trigSin/norm(trigSin);
> "

This looks correct. Make sure the output of the code is consistent with what you had earlier.
